#!/usr/bin/env zsh

# XDG
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_BIN_HOME="${HOME}/.local/bin"
export XDG_RUNTIME_DIR="${HOME}/.local/runtime"

mkdir -p ${XDG_CONFIG_HOME} ${XDG_CACHE_HOME} ${XDG_DATA_HOME} \
  ${XDG_STATE_HOME} ${XDG_BIN_HOME} ${XDG_RUNTIME_DIR}

# Zsh
export ZSH_CACHE_HOME="${XDG_CACHE_HOME}/zsh"
export ZSH_CONFIG_HOME="${XDG_CONFIG_HOME}/zsh"

mkdir -p ${ZSH_CACHE_HOME} ${ZSH_CONFIG_HOME}

if [[ -f "${HOME}/.zshrc.before" ]]; then
  source "${HOME}/.zshrc.before"
fi

source ${ZSH_CONFIG_HOME}/shell.zsh
source ${ZSH_CONFIG_HOME}/general.zsh

export PATH="${XDG_BIN_HOME}:$PATH"

source ${ZSH_CONFIG_HOME}/zinit.zsh

if [[ -f "${HOME}/.zshrc.after" ]]; then
  source "${HOME}/.zshrc.after"
fi
