#!/usr/bin/env zsh

# =========================================================== #
# XDG
# =========================================================== #

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_BIN_HOME="${HOME}/.local/bin"
export XDG_RUNTIME_DIR="${HOME}/.local/runtime"

mkdir -p ${XDG_CONFIG_HOME} ${XDG_CACHE_HOME} ${XDG_DATA_HOME} \
  ${XDG_STATE_HOME} ${XDG_BIN_HOME} ${XDG_RUNTIME_DIR}

export PATH="${XDG_BIN_HOME}:$PATH"

# Zsh
# =========================================================== #

export ZSH_CACHE_HOME="${XDG_CACHE_HOME}/zsh"
export ZSH_HOME="${XDG_CONFIG_HOME}/zsh"

mkdir -p ${ZSH_HOME} ${ZSH_CACHE_HOME}

source ${ZSH_HOME}/functions.zsh

source ${ZSH_HOME}/configs/core.zsh
source ${ZSH_HOME}/configs/general.zsh
source ${ZSH_HOME}/configs/zinit.zsh
