# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# A continuation prompt that displays two filled in arrows
continuation_prompt = '>> '

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_commit\
$line_break\
$character
"""

right_format = """
$time
"""

[username]
show_always = true
style_user = "yellow"
format = "[$user]($style)"

[hostname]
ssh_only = true
ssh_symbol = ""
style = "green"
format = "@[$ssh_symbol$hostname]($style)"

[time]
disabled = false
use_12hr = true
style = "dimmed white"
format = "[$time]($style)"

[directory]
read_only = " ro"
truncate_to_repo = false
style = "cyan bold"
format = ":[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "git:"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_commit]
tag_symbol = 'tag:'

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
